### ISSUE TITLE
Auto-deploy from Travis

### ISSUE THREAD

**Issue by glynnbird** [danmermel/cryptario#11]
When the tests pass on a merge into the master branch, Travis should deploy to Lambda.

We need to

- create a role that can deploy to Lambda
- modify .travis.yml
- do some shell script woo

This is the official way to do it:

https://docs.travis-ci.com/user/deployment/lambda/

But we might need a slightly custom one, because we need to compiled the node modules agains the Lambda docker image, so this guide might be needed:

https://gist.github.com/powerc9000/2652e6dbfbc9d428ce41531dfc0b75cb

**Comment by danmermel** [comment]
Add to the existing AWS role so it can deploy to lambda

(https://docs.travis-ci.com/user/job-lifecycle)
We want to do a "before_deploy" stuff to do the custom node npm install via docker (everything in the deploy.sh except actually deploying to lambda)


then do a "deploy" stuff in travis using their pre-packaged stuff (https://docs.travis-ci.com/user/deployment/lambda/ )

**Comment by danmermel** [comment]
need to change the directory in prepare.sh
need to add a lambda role to the yml file
need to add the handler name on the yml file
