### ISSUE TITLE
Hidden words

### ISSUE THREAD

**Issue by glynnbird** [danmermel/cryptario#25]
Stop getting letters from friends (3)
Some teachers get hurt (4)
Metal concealed by environmentalist (4)
Hide in Arthur's kingdom (4)
Who means to reveal where the heart is? (4)
Pole coming from Pakistan or Thailand (5)

**Comment by danmermel** [comment]
Need:

An index on solution
A list of hiddenWordIndicators

**Comment by danmermel** [comment]
# Stop getting letters from friends (3)

Find the indicator ("getting letters from")

Get words from left and right of indicator
"Stop"
"friends"
 
Get a list of words of the required length from left and right
sto, top.... etc
fri, rie, end,... etc

Check in the dictionary which are actual words
top
end

Are any of the actual words synonyms of the "definition" on the opposite site
top = friends?
end = stop?  BOOM!

Return "end"!

**Comment by danmermel** [comment]
# Some teachers get hurt (4)

This one the indicator is at the beginning.... so let's have some detection around the location of the indicator because then you just assume that the definition MUST be at the end

**Comment by danmermel** [comment]
TO do:

1. Write the tests for analyzeHidden
2. Return real words that fail the isSynonym test, because they may be hidden words (see Pole clue above)
