### ISSUE TITLE
Homophones

### ISSUE THREAD

**Issue by glynnbird** [danmermel/cryptario#26]
Sequence is:

Clue -  Remained sober, so we hear (6)
          We hear remained sober (6)
         An advance, we hear, on its own (5)

* Detect homophone indicator  -- "so we hear"
* Detect possible definition and subsidiary -- "Remained" + "Sober"
* Find all possible synonyms of both  Remained = stayed .... Sober = staid
* Calculate soundex of all synonyms .. stayed = S330  staid=S330
* See if any pairs of soundexes match or are close 
* Discard any pair where the length of either pair != length of solution ... stayed = 6
* Return any that are left over!

**Comment by danmermel** [comment]
Next step is to write the tests for homophone.parseClue

**Comment by danmermel** [comment]
Need tests for the AnalyzeHomophone function
We need to refine it by:
* Picking the largest indicator and discard all the others (e.g. we hear is the same as so we hear)

**Comment by danmermel** [comment]
Write a lambda function for it

**Comment by danmermel** [comment]
plumb it into the from end

**Comment by danmermel** [comment]
change terraform to create another lambda function

**Comment by danmermel** [comment]
Push into Travis and see if it builds - we have commented out tests for the travis run and also think we have a script that Travis will run
