### ISSUE TITLE
Reversals

### ISSUE THREAD

**Issue by glynnbird** [danmermel/cryptario#27]
Physician turns up fish (3)

* Find reversal indicator (turns up)
* Find potential definition and subsidiary (physician ... fish)
* Find synonyms one side, e.g. fish = cod, halibut, swordfish, rib, pez)
* Throw away any that are not three letters long 
* reverse any that are left (cod = doc, rib=bir, pez = zep)
* See if any are synonyms of the other side (doc = physician)
* Return all of them anyway, but the synonym=true ones at the top

**Comment by danmermel** [comment]
We need to present some commentary for the humans...

also, why did it come back with cod instead of doc

**Comment by danmermel** [comment]
Also need tests
