### ISSUE TITLE
Containers and Contents

### ISSUE THREAD

**Issue by glynnbird** [danmermel/cryptario#29]

**Comment by danmermel** [comment]
Object when put into torn clothing (7)
(Raiment)

**Comment by danmermel** [comment]
Find indicator (outside)
The words either side of indicator need to be synonymised (allowed / tavern)
Definition is derived from there - remembering that the definition is only ever the first or last word, then if the word to one side of the indicator is the last or first, then that cannot be the definition

(at this point we may have one or two potential definitions).
For each one:
Calculate the synonyms of the words either side of indicator 
allowed = permitted, able, let
tavern = bar, inn, restaurant

Make pairs with all (i.e. permittedbar, permittedinn, permittedrestaurant) and throw away anything larger than solution length
left with things like letbar, letinn

Anagram them all and get some actual six-letter words out
e.g. linnet, bralet, lebrat, lebart

For each one, check that it contains one of the synonyms you got earlier:
so you are left with linnet, lebart 

Finally check if any of those are synonyms of the definition
(but we return all of those anyway to the user)

**Comment by danmermel** [comment]
Return the object in the standard form

**Comment by danmermel** [comment]
Think about multiword subsidiaries

**Comment by danmermel** [comment]
Tests

**Comment by danmermel** [comment]
The tests in doubledef and hidden words are broken because the returned object has changed

**Comment by danmermel** [comment]
Do the plumbing work (api call, lambda, etc)
